version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10-browsers
    working_directory: /usr/src
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            npm run build:ci
